apiVersion: v1
kind: ConfigMap
metadata:
  name: getfile
data:
  getfile.sh: |+
    set -e
    set -x

    printf "[Credentials]\ngs_access_key_id = $GS_ACCESS\ngs_secret_access_key=$GS_SECRET\n[Boto]\nhttps_validate_certificates = True\n[GSUtil]\ncontent_language = en\ndefault_api_version = 2\ndefault_project_id = nimble-valve-236407" > ~/.boto

    mkdir /tmp/inputs
    echo ${CMS_INPUT_FILES}|tr ',' '\n'|while read x;do
      gsutil cp $x /tmp/inputs
    done
