apiVersion: v1
kind: Namespace
metadata:
  name: prepull
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
  namespace: prepull
spec:
  selector:
    matchLabels:
      name: prepull
  template:
    metadata:
      labels:
        name: prepull
    spec:
      initContainers:
      - name: prepull
        image: gcr.io/nimble-valve-236407/cms-higgs-4l-full
      - name: prepull-worker
        image: gcr.io/nimble-valve-236407/worker
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
