apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: prepull
  template:
    metadata:
      labels:
        name: prepull
    spec:
      initContainers:
      - name: prepull
        image: gcr.io/nimble-valve-236407/cms-higgs-4l-full
        command: ["bash", "-c", "sleep", "1"]
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
